import 'dart:convert';
import "dart:io";

import 'package:recase/recase.dart';

void main(List<String> args) {
  File fontsPreviewFile = File(args[0]);
  final aliasMap = loadAliasMap(
    Directory('lucide/lucide-source/icons'),
  );

  if (!fontsPreviewFile.existsSync()) {
    print('lucide preview file not found');
    exit(0);
  }

  String content = fontsPreviewFile.readAsStringSync();

  Map<String, dynamic> jsonMap = json.decode(content);
  Map<String, Map<String, String>> result = {};

  jsonMap.forEach((key, value) {
    if (value is Map<String, String>) {
      result[key] = Map<String, String>.from(value);
    }
  });

  List<Map<dynamic, dynamic>> resultList = jsonMap.entries
      .map((entry) => {'name': entry.key, ...entry.value})
      .toList();
  // stdout.write("info message1 ${resultList}");
  // final c = parse(content);
  // final list = c.getElementsByClassName('glyph');

  List<String> generatedOutput = [
    "library lucide_icons;\n",
    "import \"package:flutter/widgets.dart\";\n\n",
    "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
    "/// Lucide Icons\n",
    "class LucideIcons {\n",
    "/// Private constructor to prevent instantiation.\n",
    "/// This class is intended solely for organizing static icon definitions.\n",
    "/// Making the constructor private stops the IDE from suggesting object creation.\n",
    "const LucideIcons._();\n\n",
  ];
  List<String> listIconTest = [
    "\nimport 'package:flutter/material.dart';",
    "\nimport 'package:lucide_icons_flutter/lucide_icons.dart';",
    "\n/// Lucide Icons",
    "\nList<IconData> icons = ["
  ];
  final generatedCanonicalNames = <String>{};

  for (Map data in resultList) {
    final iconName = data['name'] as String;
    final canonicalIconName =
        aliasMap[normalizeIconName(iconName)] ?? normalizeIconName(iconName);

    if (!generatedCanonicalNames.add(canonicalIconName)) {
      continue;
    }

    final baseVarName = buildIconVariableName(canonicalIconName);
    String svgContent = loadSvgContent(
      iconName: canonicalIconName,
      svgPath: 'lucide/lucide-source/icons/$canonicalIconName.svg',
    );

    if (svgContent.isEmpty) {
      // Tạo một SVG đơn giản nếu không tìm thấy file
      print('Không tìm thấy SVG cho $canonicalIconName');
      String fallbackSvg =
          '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#ff0000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>';
      svgContent = base64Encode(utf8.encode(fallbackSvg));
    }

    // Sử dụng URL data với định dạng đầy đủ
    // Sinh biến gốc (không kèm fontFamily)
    generatedOutput.add("/// $canonicalIconName\n" +
        "/// ![$canonicalIconName](data:image/svg+xml;base64,${svgContent})\n" +
        "static const IconData $baseVarName = ${buildIconDataLiteral(codePoint: parseUnicodeString(data['unicode']))};\n");
    listIconTest.add("\nLucideIcons.$baseVarName,");

    // Sinh thêm các biến với fontFamily Lucide100...Lucide600
    for (int i = 100; i <= 600; i += 100) {
      String svgContent = loadSvgContent(
        iconName: canonicalIconName,
        svgPath: 'lucide/svg_input/weight$i/$canonicalIconName.svg',
      );

      if (svgContent.isEmpty) {
        // Tạo một SVG đơn giản nếu không tìm thấy file
        print('Không tìm thấy SVG cho $canonicalIconName');
        String fallbackSvg =
            '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#ff0000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>';
        svgContent = base64Encode(utf8.encode(fallbackSvg));
      }

      String fontFamily = 'Lucide$i';
      final varName = buildWeightedIconVariableName(baseVarName, i);
      generatedOutput.add("/// $canonicalIconName với fontFamily $fontFamily\n"
          "/// ![$canonicalIconName](data:image/svg+xml;base64,${svgContent})\n"
          "static const IconData $varName = ${buildIconDataLiteral(codePoint: parseUnicodeString(data['unicode']), fontFamily: fontFamily)};\n");
      listIconTest.add("\nLucideIcons.$varName,");
    }
  }
  // print('$val $name');
  // }

  generatedOutput.add("}\n");
  listIconTest.add("];");
  //  stdout.write("info message2 ${generatedOutput}");

  File output = File('../lib/lucide_icons.dart');
  output.writeAsStringSync(generatedOutput.join());
  File outputTest = File('../lib/test_icons.dart');
  outputTest.writeAsStringSync(listIconTest.join());
}

int parseUnicodeString(String unicodeString) {
  // Remove the '&#' prefix and ';' suffix from the string
  String hexString = unicodeString.substring(2, unicodeString.length - 1);

  // Parse the hexadecimal string and convert it to an integer
  int unicodeInt = int.parse(hexString);

  return unicodeInt;
}

String buildIconDataLiteral({
  required int codePoint,
  String fontFamily = 'Lucide',
  bool matchTextDirection = false,
}) {
  final buffer = StringBuffer(
    "const IconData($codePoint, fontFamily: '$fontFamily', fontPackage: 'lucide_icons_flutter'",
  );

  if (matchTextDirection) {
    buffer.write(', matchTextDirection: true');
  }

  buffer.write(')');
  return buffer.toString();
}

String buildIconVariableName(String iconName) {
  return ReCase(iconName).camelCase;
}

String buildWeightedIconVariableName(String baseVarName, int weight) {
  if (RegExp(r'\d$').hasMatch(baseVarName)) {
    return '${baseVarName}Weight$weight';
  }

  return '$baseVarName$weight';
}

int parseUnicodeString2(String unicodeString) {
  // Remove the '\\' prefix from the string
  String hexString = unicodeString.substring(2);

  // Parse the hexadecimal string and convert it to an integer
  int unicodeInt = int.parse(hexString, radix: 16);

  return unicodeInt;
}

String normalizeIconName(String iconName) {
  return iconName.replaceAll('icon-', '');
}

Map<String, String> loadAliasMap(Directory iconsDirectory) {
  final aliasMap = <String, String>{};

  if (!iconsDirectory.existsSync()) {
    return aliasMap;
  }

  for (final entity in iconsDirectory.listSync()) {
    if (entity is! File || !entity.path.endsWith('.json')) {
      continue;
    }

    final canonicalName =
        entity.uri.pathSegments.last.replaceFirst(RegExp(r'\.json$'), '');
    final jsonData = jsonDecode(entity.readAsStringSync());

    if (jsonData is! Map<String, dynamic>) {
      continue;
    }

    final aliases = jsonData['aliases'];
    if (aliases is! List) {
      continue;
    }

    for (final alias in aliases) {
      if (alias is! Map<String, dynamic>) {
        continue;
      }

      final aliasName = alias['name'];
      if (aliasName is String && aliasName.isNotEmpty) {
        aliasMap[aliasName] = canonicalName;
      }
    }
  }

  return aliasMap;
}

String loadSvgContent({
  required String iconName,
  required String svgPath,
}) {
  try {
    final svgFile = File(svgPath);
    if (!svgFile.existsSync()) {
      return '';
    }

    String svgContent = svgFile.readAsStringSync();
    svgContent = svgContent
        .replaceAll('stroke="currentColor"', 'stroke="#0066cc"')
        .replaceAll('width="24"', 'width="48"')
        .replaceAll('height="24"', 'height="48"');

    if (!svgContent.contains('xmlns="http://www.w3.org/2000/svg"')) {
      svgContent = svgContent.replaceFirst(
          '<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
    }

    svgContent = svgContent.replaceFirst('<svg', '<svg version="1.1"');
    return base64Encode(utf8.encode(svgContent));
  } catch (e) {
    print('Không thể đọc SVG cho $iconName: $e');
    return '';
  }
}
