import 'dart:convert';
import 'dart:io';
import 'package:recase/recase.dart';

void main() {
  File glyphFile =
      File('tool/remix_source/RemixIcon-4.7.0/fonts/remixicon.glyph.json');

  if (!glyphFile.existsSync()) {
    print('remixicon.glyph.json not found');
    exit(1);
  }

  String content = glyphFile.readAsStringSync();
  Map<String, dynamic> jsonMap = json.decode(content);

  Map<String, File> iconFiles = {};
  Directory iconsDir = Directory('tool/remix_source/RemixIcon-4.7.0/icons');
  if (iconsDir.existsSync()) {
    List<FileSystemEntity> entities = iconsDir.listSync(recursive: true);
    for (var entity in entities) {
      if (entity is File && entity.path.endsWith('.svg')) {
        String name = entity.uri.pathSegments.last.replaceAll('.svg', '');
        iconFiles[name] = entity;
      }
    }
  }

  List<String> generatedOutput = [
    "library remix_icon;\n",
    "import 'package:flutter/widgets.dart';\n",
    "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
    "class RemixIcon {\n",
    "  const RemixIcon._();\n\n",
    "  static const String _fontFamily = 'RemixIcon';\n",
    "  static const String? _fontPackage = 'remixiconflutter';\n\n",
  ];

  jsonMap.forEach((key, value) {
    String unicodeString = value['unicode'];
    // Format is &#xEA01;
    String hex = unicodeString.replaceAll('&#x', '').replaceAll(';', '');
    // int codePoint is unused, remove it to fix lint
    // int codePoint = int.parse(hex, radix: 16);
    String varName = ReCase(key).camelCase;

    // Some names might start with numbers, e.g. "24-hours". ReCase handles it but Dart variables can't start with numbers.
    if (varName.startsWith(RegExp(r'[0-9]'))) {
      varName = 'i$varName'; // Prefix with 'i' or similar
    }
    // Reserved words check? 'try' is unlikely but possible.

    String comment = '/// $key\n';
    if (iconFiles.containsKey(key)) {
      try {
        String svgContent = iconFiles[key]!.readAsStringSync();
        if (!svgContent.contains('xmlns="http://www.w3.org/2000/svg"')) {
          svgContent = svgContent.replaceFirst(
              '<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
        }
        String base64Svg = base64Encode(utf8.encode(svgContent));
        comment += '/// ![$key](data:image/svg+xml;base64,$base64Svg)\n';
      } catch (e) {
        print('Error reading/encoding SVG for $key: $e');
      }
    }

    generatedOutput.add(
        "$comment  static const IconData $varName = IconData(0x$hex, fontFamily: _fontFamily, fontPackage: _fontPackage);\n");
  });

  generatedOutput.add("}\n");

  File output = File('lib/remixicon_ids.dart');
  output.writeAsStringSync(generatedOutput.join());

  List<String> listOutput = [
    "import 'package:flutter/widgets.dart';\n",
    "import 'package:remixiconflutter/remixicon_ids.dart';\n\n",
    "List<IconData> allIcons = [\n"
  ];

  jsonMap.forEach((key, value) {
    String varName = ReCase(key).camelCase;
    if (varName.startsWith(RegExp(r'[0-9]'))) {
      varName = 'i$varName';
    }
    listOutput.add("  RemixIcon.$varName,\n");
  });

  listOutput.add("];\n");

  File listFile = File('lib/remixicon_list.dart');
  listFile.writeAsStringSync(listOutput.join());

  print(
      'Generated ${jsonMap.length} icons to lib/remixicon_ids.dart and lib/remixicon_list.dart');
}
