import 'dart:convert';
import 'dart:io';

import 'package:recase/recase.dart';

const weights = [100, 200, 300, 400, 500, 600];
const fontPackage = 'lucide_icons_flutter';

void main(List<String> args) {
  final repoRoot = findRepoRoot();
  final inputFile = resolveInputFile(args, repoRoot);

  if (!inputFile.existsSync()) {
    stderr.writeln('lucide info file not found: ${inputFile.path}');
    exit(66);
  }

  final jsonMap = json.decode(inputFile.readAsStringSync());
  if (jsonMap is! Map<String, dynamic>) {
    stderr.writeln('Invalid lucide info file: expected a JSON object.');
    exit(65);
  }

  final generatedOutput = <String>[
    "library lucide_icons;\n",
    "import 'package:flutter/widgets.dart';\n\n",
    "export 'src/lucide_icon_widget.dart';\n\n",
    "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
    "/// Lucide Icons\n",
    "class LucideIcons {\n",
    "  const LucideIcons._();\n\n",
  ];

  final listIconTest = <String>[
    "import 'package:flutter/widgets.dart';\n",
    "import 'package:lucide_icons_flutter/lucide_icons.dart';\n\n",
    "List<IconData> icons = [\n",
  ];

  final entries = jsonMap.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));

  for (final entry in entries) {
    final value = entry.value;
    if (value is! Map<String, dynamic>) {
      continue;
    }

    final unicode = value['unicode'];
    if (unicode is! String) {
      continue;
    }

    final baseName = safeDartName(ReCase(entry.key).camelCase);
    final codePoint = parseUnicodeString(unicode);

    generatedOutput.add("  /// ${entry.key}\n");
    for (final weight in weights) {
      final iconName = '$baseName$weight';
      generatedOutput.add(
        "  static const IconData $iconName = const IconData($codePoint,\n"
        "      fontFamily: 'Lucide$weight',\n"
        "      fontPackage: '$fontPackage');\n",
      );
      listIconTest.add("  LucideIcons.$iconName,\n");
    }
  }

  generatedOutput.add("}\n");
  listIconTest.add("];\n");

  File('${repoRoot.path}/lib/lucide_icons.dart')
      .writeAsStringSync(generatedOutput.join());
  File('${repoRoot.path}/lib/test_icons.dart').writeAsStringSync(
    listIconTest.join(),
  );
}

File resolveInputFile(List<String> args, Directory repoRoot) {
  if (args.isNotEmpty) {
    final file = File(args.first);
    if (file.isAbsolute) {
      return file;
    }
    return File('${Directory.current.path}/${args.first}');
  }

  return File('${repoRoot.path}/assets/info.json');
}

Directory findRepoRoot() {
  var current = Directory.current.absolute;

  while (true) {
    if (File('${current.path}/pubspec.yaml').existsSync()) {
      return current;
    }

    final parent = current.parent;
    if (parent.path == current.path) {
      throw StateError('Khong tim thay pubspec.yaml de xac dinh repo root.');
    }

    current = parent;
  }
}

int parseUnicodeString(String unicodeString) {
  final match = RegExp(r'&#x?([0-9a-fA-F]+);').firstMatch(unicodeString);
  if (match == null) {
    throw FormatException('Invalid unicode value', unicodeString);
  }

  final digits = match.group(1)!;
  final radix = unicodeString.startsWith('&#x') ? 16 : 10;
  return int.parse(digits, radix: radix);
}

String safeDartName(String name) {
  if (name.startsWith(RegExp(r'[0-9]'))) {
    return 'i$name';
  }

  return name;
}
