import 'dart:convert';
import "dart:io";

import 'package:recase/recase.dart';

void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln(
        'Usage: dart run tool/generate_fonts_1.dart <path-to-info.json>');
    exit(64);
  }

  final repoRoot = findRepoRoot();
  final iconsDirectory =
      Directory('${repoRoot.path}/tool/lucide/lucide-source/icons');
  final fontsPreviewFile = resolveInputFile(args[0]);
  final sourceIconNames = loadSourceIconNames(iconsDirectory);

  if (!fontsPreviewFile.existsSync()) {
    print('lucide preview file not found');
    exit(0);
  }

  String content = fontsPreviewFile.readAsStringSync();

  Map<String, dynamic> jsonMap = json.decode(content);
  Map<String, Map<String, String>> result = {};

  jsonMap.forEach((key, value) {
    if (value is Map<String, String>) {
      result[key] = Map<String, String>.from(value);
    }
  });

  List<Map<dynamic, dynamic>> resultList = jsonMap.entries
      .map((entry) => {'name': entry.key, ...entry.value})
      .toList();
  // stdout.write("info message1 ${resultList}");
  // final c = parse(content);
  // final list = c.getElementsByClassName('glyph');

  List<String> generatedOutput = [
    "library lucide_icons;\n",
    "import \"package:flutter/widgets.dart\";\n",
    "import \"src/icon_data.dart\";\n",
    "export \"src/icon_exten.dart\";\n\n",
    "// THIS FILE IS AUTOMATICALLY GENERATED!\n\n",
    "/// Lucide Icons\n",
    "class LucideIcons {\n",
    "/// Private constructor to prevent instantiation.\n",
    "/// This class is intended solely for organizing static icon definitions.\n",
    "/// Making the constructor private stops the IDE from suggesting object creation.\n",
    "const LucideIcons._();\n\n",
  ];
  List<String> listIconTest = [
    "\nimport 'package:flutter/material.dart';",
    "\nimport 'package:lucide_icons_flutter/lucide_icons.dart';",
    "\n/// Lucide Icons",
    "\nList<IconData> icons = ["
  ];
  for (Map data in resultList) {
    String iconName = data['name'];
    final normalizedIconName = normalizeIconName(iconName);

    // Chỉ generate icon canonical đang còn tồn tại trong source Lucide hiện tại.
    // assets/info.json vẫn chứa nhiều alias/deprecated names cũ; nếu sinh cả chúng
    // thì các tên như arrow-down-1-0 và arrow-down-10 sẽ cùng thành arrowDown10.
    if (!sourceIconNames.contains(normalizedIconName)) {
      continue;
    }

    final baseVarName = buildIconVariableName(iconName);
    String svgContent = loadSvgContent(
      iconName: iconName,
      svgPath:
          '${repoRoot.path}/tool/lucide/lucide-source/icons/$normalizedIconName.svg',
    );

    if (svgContent.isEmpty) {
      // Tạo một SVG đơn giản nếu không tìm thấy file
      print('Không tìm thấy SVG cho $iconName');
      String fallbackSvg =
          '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#ff0000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>';
      svgContent = base64Encode(utf8.encode(fallbackSvg));
    }

    // Sử dụng URL data với định dạng đầy đủ
    // Sinh biến gốc (không kèm fontFamily)
    generatedOutput.add("/// ${data['name']}\n" +
        "/// ![${data['name']}](data:image/svg+xml;base64,${svgContent})\n" +
        "static const IconData $baseVarName = const LucideIconData(${parseUnicodeString(data['unicode'])});\n");
    listIconTest.add("\nLucideIcons.$baseVarName,");

    // Sinh thêm các biến với fontFamily Lucide100...Lucide600
    for (int i = 100; i <= 600; i += 100) {
      String svgContent = loadSvgContent(
        iconName: iconName,
        svgPath:
            '${repoRoot.path}/tool/lucide/svg_input/weight$i/$normalizedIconName.svg',
      );

      if (svgContent.isEmpty) {
        // Tạo một SVG đơn giản nếu không tìm thấy file
        print('Không tìm thấy SVG cho $iconName');
        String fallbackSvg =
            '<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#ff0000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>';
        svgContent = base64Encode(utf8.encode(fallbackSvg));
      }

      String fontFamily = 'Lucide$i';
      String varName = buildWeightVariableName(baseVarName, i);
      generatedOutput.add("/// ${data['name']} với fontFamily $fontFamily\n"
          "/// ![${data['name']}](data:image/svg+xml;base64,${svgContent})\n"
          "static const IconData $varName = const LucideIconData(${parseUnicodeString(data['unicode'])}, fontFamily: '$fontFamily');\n");
      listIconTest.add("\nLucideIcons.$varName,");
    }
  }
  // print('$val $name');
  // }

  generatedOutput.add("}\n");
  listIconTest.add("];");
  //  stdout.write("info message2 ${generatedOutput}");

  File output = File('${repoRoot.path}/lib/lucide_icons.dart');
  output.writeAsStringSync(generatedOutput.join());
  File outputTest = File('${repoRoot.path}/lib/test_icons.dart');
  outputTest.writeAsStringSync(listIconTest.join());
}

int parseUnicodeString(String unicodeString) {
  // Remove the '&#' prefix and ';' suffix from the string
  String hexString = unicodeString.substring(2, unicodeString.length - 1);

  // Parse the hexadecimal string and convert it to an integer
  int unicodeInt = int.parse(hexString);

  return unicodeInt;
}

int parseUnicodeString2(String unicodeString) {
  // Remove the '\\' prefix from the string
  String hexString = unicodeString.substring(2);

  // Parse the hexadecimal string and convert it to an integer
  int unicodeInt = int.parse(hexString, radix: 16);

  return unicodeInt;
}

String normalizeIconName(String iconName) {
  return iconName.replaceAll('icon-', '');
}

String buildIconVariableName(String iconName) {
  return ReCase(iconName).camelCase;
}

String buildWeightVariableName(String baseVarName, int weight) {
  if (RegExp(r'\d$').hasMatch(baseVarName)) {
    return '${baseVarName}Weight$weight';
  }

  return '$baseVarName$weight';
}

Directory findRepoRoot() {
  var current = Directory.current.absolute;

  while (true) {
    if (File('${current.path}/pubspec.yaml').existsSync()) {
      return current;
    }

    final parent = current.parent;
    if (parent.path == current.path) {
      throw StateError('Không tìm thấy pubspec.yaml để xác định repo root.');
    }

    current = parent;
  }
}

File resolveInputFile(String filePath) {
  final inputFile = File(filePath);
  if (inputFile.isAbsolute) {
    return inputFile;
  }

  return File('${Directory.current.path}/$filePath');
}

Set<String> loadSourceIconNames(Directory iconsDirectory) {
  if (!iconsDirectory.existsSync()) {
    return const <String>{};
  }

  return iconsDirectory
      .listSync()
      .whereType<File>()
      .where((file) => file.path.endsWith('.svg'))
      .map((file) => file.uri.pathSegments.last.replaceFirst('.svg', ''))
      .toSet();
}

String loadSvgContent({
  required String iconName,
  required String svgPath,
}) {
  try {
    final svgFile = File(svgPath);
    if (!svgFile.existsSync()) {
      return '';
    }

    String svgContent = svgFile.readAsStringSync();
    svgContent = svgContent
        .replaceAll('stroke="currentColor"', 'stroke="#0066cc"')
        .replaceAll('width="24"', 'width="48"')
        .replaceAll('height="24"', 'height="48"');

    if (!svgContent.contains('xmlns="http://www.w3.org/2000/svg"')) {
      svgContent = svgContent.replaceFirst(
          '<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
    }

    svgContent = svgContent.replaceFirst('<svg', '<svg version="1.1"');
    return base64Encode(utf8.encode(svgContent));
  } catch (e) {
    print('Không thể đọc SVG cho $iconName: $e');
    return '';
  }
}
